table dim_customer
	lineageTag: 4586de62-ddca-424d-9255-b8f4b98e1782

	column customer_key
		dataType: int64
		formatString: 0
		lineageTag: 102c699b-4025-402d-905a-2bd50451cc8b
		sourceColumn: customer_key

		annotation SummarizationSetBy = None

	column customer_source_id
		dataType: string
		lineageTag: f5582cd3-4af6-4e3b-98fd-8014dec1ae79
		sourceColumn: customer_source_id

		annotation SummarizationSetBy = Automatic

	column customer_segment
		dataType: string
		lineageTag: 4b6a943b-92e5-44ed-a248-653f2e8db415
		sourceColumn: customer_segment

		annotation SummarizationSetBy = Automatic

	column location_key
		dataType: int64
		formatString: 0
		lineageTag: 5659c2b9-4214-4e7b-85fe-be9f75d628b4
		sourceColumn: location_key

		annotation SummarizationSetBy = Automatic

	column signup_date_key
		dataType: int64
		formatString: 0
		lineageTag: 9d76a0df-62a7-4a84-a16f-284b4c30b10f
		sourceColumn: signup_date_key

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\dim_customer.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"customer_key", Int64.Type}, {"customer_source_id", type text}, {"customer_segment", type text}, {"location_key", Int64.Type}, {"signup_date_key", Int64.Type}})
				in
					Typed
