table dim_product
	lineageTag: 859f5bbe-044a-4494-9071-00f06ba5d124

	column product_key
		dataType: int64
		formatString: 0
		sourceColumn: product_key

		annotation SummarizationSetBy = None

	column product_source_id
		dataType: string
		sourceColumn: product_source_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column subcategory
		dataType: string
		sourceColumn: subcategory

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column unit_cost
		dataType: double
		formatString: #,0.00
		sourceColumn: unit_cost

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column supplier_key
		dataType: int64
		formatString: 0
		sourceColumn: supplier_key

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\dim_product.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"product_key", Int64.Type}, {"product_source_id", type text}, {"product_name", type text}, {"category", type text}, {"subcategory", type text}, {"brand", type text}, {"unit_cost", type number}, {"unit_price", type number}, {"supplier_key", Int64.Type}})
				in
					Typed
