table dim_location
	lineageTag: e83129cd-ac45-41c7-92ba-11a391bea0ec

	column location_key
		dataType: int64
		formatString: 0
		sourceColumn: location_key

		annotation SummarizationSetBy = None

	column emirate
		dataType: string
		sourceColumn: emirate

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region_source
		dataType: string
		sourceColumn: region_source

		annotation SummarizationSetBy = Automatic

	partition dim_location = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\dim_location.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"location_key", Int64.Type}, {"emirate", type text}, {"city", type text}, {"region_source", type text}})
				in
					Typed
