table dim_location
	lineageTag: e83129cd-ac45-41c7-92ba-11a391bea0ec

	column location_key
		dataType: int64
		formatString: 0
		lineageTag: e1b3df42-41ec-4663-b93e-2d49a79f22a9
		sourceColumn: location_key

		annotation SummarizationSetBy = None

	column emirate
		dataType: string
		lineageTag: 4e9972a0-7502-4919-b0c1-60da8777e08f
		sourceColumn: emirate

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 38f38a9d-6294-4670-96af-93cbf60d407c
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column region_source
		dataType: string
		lineageTag: 97483119-dcb4-4518-8bf1-beaf1276ad80
		sourceColumn: region_source

		annotation SummarizationSetBy = Automatic

	partition dim_location = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\dim_location.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"location_key", Int64.Type}, {"emirate", type text}, {"city", type text}, {"region_source", type text}})
				in
					Typed
