table dim_warehouse
	lineageTag: f8ba6ddc-1467-48eb-a8c0-49190a0d1fb8

	column warehouse_key
		dataType: int64
		formatString: 0
		lineageTag: 15c6fffd-7e11-4421-b02c-5ff777a04830
		sourceColumn: warehouse_key

		annotation SummarizationSetBy = None

	column warehouse_source_id
		dataType: string
		lineageTag: 97ba6207-a338-424e-bc52-38b8c83c9e8f
		sourceColumn: warehouse_source_id

		annotation SummarizationSetBy = Automatic

	column warehouse_name
		dataType: string
		lineageTag: 79f41db9-1878-42cf-b1fc-6057c40fbd97
		sourceColumn: warehouse_name

		annotation SummarizationSetBy = Automatic

	column location_key
		dataType: int64
		formatString: 0
		lineageTag: 283a2113-e9b6-4971-b173-43b54175ad53
		sourceColumn: location_key

		annotation SummarizationSetBy = Automatic

	column capacity_units
		dataType: int64
		formatString: 0
		lineageTag: dff4d453-1ecc-4b3c-b51a-924a27f8abf6
		sourceColumn: capacity_units

		annotation SummarizationSetBy = Automatic

	partition dim_warehouse = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\dim_warehouse.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"warehouse_key", Int64.Type}, {"warehouse_source_id", type text}, {"warehouse_name", type text}, {"location_key", Int64.Type}, {"capacity_units", Int64.Type}})
				in
					Typed
