table fact_returns
	lineageTag: 611eb6e2-111a-43db-9f85-27c179a9c1c0

	column return_key
		dataType: int64
		formatString: 0
		lineageTag: 57739820-0d91-4232-a908-bd83a97eb0cc
		sourceColumn: return_key

		annotation SummarizationSetBy = None

	column sales_key
		dataType: int64
		formatString: 0
		lineageTag: 5cdff11c-56c9-40f0-a022-209aaf577e68
		sourceColumn: sales_key

		annotation SummarizationSetBy = Automatic

	column return_date_key
		dataType: int64
		formatString: 0
		lineageTag: f4c04251-74a0-4be0-bd1d-8c67a5be8131
		sourceColumn: return_date_key

		annotation SummarizationSetBy = Automatic

	column reason
		dataType: string
		lineageTag: cd9d9132-f430-451a-8fab-2457d19d11b5
		sourceColumn: reason

		annotation SummarizationSetBy = Automatic

	column returned_quantity
		dataType: int64
		formatString: #,0
		lineageTag: c7fc9767-3614-4a7e-9cb9-5c3609ff790a
		sourceColumn: returned_quantity

		annotation SummarizationSetBy = Automatic

	column refund_amount
		dataType: double
		formatString: #,0.00
		lineageTag: 7b4ada79-88d4-4011-8d00-6e9ac198878c
		sourceColumn: refund_amount

		annotation SummarizationSetBy = Automatic

	partition fact_returns = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\fact_returns.csv"), [Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"return_key", Int64.Type}, {"sales_key", Int64.Type}, {"return_date_key", Int64.Type}, {"reason", type text}, {"returned_quantity", Int64.Type}, {"refund_amount", type number}})
				in
					Typed
