table fact_purchase_orders
	lineageTag: 57a430e9-3e02-4144-8064-4472c29bffda

	column po_key
		dataType: int64
		formatString: 0
		sourceColumn: po_key

		annotation SummarizationSetBy = None

	column po_source_id
		dataType: string
		sourceColumn: po_source_id

		annotation SummarizationSetBy = Automatic

	column supplier_key
		dataType: int64
		formatString: 0
		sourceColumn: supplier_key

		annotation SummarizationSetBy = Automatic

	column warehouse_key
		dataType: int64
		formatString: 0
		sourceColumn: warehouse_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		formatString: 0
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column order_date_key
		dataType: int64
		formatString: 0
		sourceColumn: order_date_key

		annotation SummarizationSetBy = Automatic

	column expected_delivery_date_key
		dataType: int64
		formatString: 0
		sourceColumn: expected_delivery_date_key

		annotation SummarizationSetBy = Automatic

	column actual_delivery_date_key
		dataType: int64
		formatString: 0
		sourceColumn: actual_delivery_date_key

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: #,0
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_cost
		dataType: double
		formatString: #,0.00
		sourceColumn: unit_cost

		annotation SummarizationSetBy = Automatic

	column total_cost
		dataType: double
		formatString: #,0.00
		sourceColumn: total_cost

		annotation SummarizationSetBy = Automatic

	partition fact_purchase_orders = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\fact_purchase_orders.csv"), [Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"po_key", Int64.Type}, {"po_source_id", type text}, {"supplier_key", Int64.Type}, {"warehouse_key", Int64.Type}, {"product_key", Int64.Type}, {"order_date_key", Int64.Type}, {"expected_delivery_date_key", Int64.Type}, {"actual_delivery_date_key", Int64.Type}, {"order_status", type text}, {"quantity", Int64.Type}, {"unit_cost", type number}, {"total_cost", type number}})
				in
					Typed
