table fact_inventory
	lineageTag: ae13362a-db59-48a3-8d51-ac6a4d3bec02

	column inventory_key
		dataType: int64
		formatString: 0
		lineageTag: d5fc0516-99b9-4298-9a22-1f310b6a4794
		sourceColumn: inventory_key

		annotation SummarizationSetBy = None

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 97116859-81d6-4f10-bef7-5de8d73e6a4c
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: b3082ddc-b497-4406-a387-aada6866f860
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column warehouse_key
		dataType: int64
		formatString: 0
		lineageTag: 913c76d5-bf50-450c-9ab2-75c1280150f5
		sourceColumn: warehouse_key

		annotation SummarizationSetBy = Automatic

	column opening_stock
		dataType: int64
		formatString: #,0
		lineageTag: f39b0fb0-8e4a-4de0-9c76-5da85f7d8fda
		sourceColumn: opening_stock

		annotation SummarizationSetBy = Automatic

	column received_quantity
		dataType: int64
		formatString: #,0
		lineageTag: 1f19ed9e-3c7b-4639-a3ca-e014fcca8dbf
		sourceColumn: received_quantity

		annotation SummarizationSetBy = Automatic

	column sold_quantity
		dataType: int64
		formatString: #,0
		lineageTag: d4f7b51a-1f27-4726-ad86-dd192b46e66b
		sourceColumn: sold_quantity

		annotation SummarizationSetBy = Automatic

	column closing_stock
		dataType: int64
		formatString: #,0
		lineageTag: 60eefa93-b195-4609-898a-fdc94e0e8458
		sourceColumn: closing_stock

		annotation SummarizationSetBy = Automatic

	partition fact_inventory = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\fact_inventory.csv"), [Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"inventory_key", Int64.Type}, {"date_key", Int64.Type}, {"product_key", Int64.Type}, {"warehouse_key", Int64.Type}, {"opening_stock", Int64.Type}, {"received_quantity", Int64.Type}, {"sold_quantity", Int64.Type}, {"closing_stock", Int64.Type}})
				in
					Typed
