table fact_sales
	lineageTag: f3b03f31-a1cc-433d-9bc5-518a08a6cad8

	column sales_key
		dataType: int64
		formatString: 0
		sourceColumn: sales_key

		annotation SummarizationSetBy = None

	column source_system
		dataType: string
		sourceColumn: source_system

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_line_item_id
		dataType: string
		sourceColumn: order_line_item_id

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		formatString: 0
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column customer_key
		dataType: int64
		formatString: 0
		sourceColumn: customer_key

		annotation SummarizationSetBy = Automatic

	column location_key
		dataType: int64
		formatString: 0
		sourceColumn: location_key

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: int64
		formatString: 0
		sourceColumn: store_key

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: #,0
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: double
		formatString: #,0.00
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column discount
		dataType: double
		formatString: #,0.00
		sourceColumn: discount

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		formatString: #,0.00
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column delivery_status
		dataType: string
		sourceColumn: delivery_status

		annotation SummarizationSetBy = Automatic

	column original_currency
		dataType: string
		sourceColumn: original_currency

		annotation SummarizationSetBy = Automatic

	column original_sales_amount
		dataType: double
		formatString: #,0.00
		sourceColumn: original_sales_amount

		annotation SummarizationSetBy = Automatic

	partition fact_sales = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(RepoRoot & "powerbi\data\fact_sales.csv"), [Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Promoted, {{"sales_key", Int64.Type}, {"source_system", type text}, {"order_id", type text}, {"order_line_item_id", type text}, {"date_key", Int64.Type}, {"product_key", Int64.Type}, {"customer_key", Int64.Type}, {"location_key", Int64.Type}, {"store_key", Int64.Type}, {"quantity", Int64.Type}, {"unit_price", type number}, {"discount", type number}, {"sales_amount", type number}, {"order_status", type text}, {"delivery_status", type text}, {"original_currency", type text}, {"original_sales_amount", type number}})
				in
					Typed
